// Product catalogue — sourced from the Tirupati Associates catalogue (10 categories, in catalogue order).
// Consumed by /products (category tabs), /products/[slug] (item detail), the sitemap and the footer.

export type CatalogItem = {
  code: string; // internal catalogue reference (used only for the image file name)
  num: string;
  slug: string;
  name: string;
  material: string;
  finish: string;
  size: string;
  image: string;
  desc: string;
};

export type CatalogCategory = {
  slug: string;
  num: string;
  name: string;
  single: string;
  tagline: string;
  desc: string;
  items: CatalogItem[];
};

const item = (code: string, name: string, material: string, finish: string, size = ""): CatalogItem => ({
  code,
  num: "",
  slug: "",
  name,
  material,
  finish,
  size,
  image: `/img/products/${code.toLowerCase()}.jpg`,
  desc: "",
});

const rawCategories: CatalogCategory[] = [
  {
    slug: "hinges",
    num: "01",
    name: "Hinges",
    single: "Hinge",
    tagline: "Classic hinges in multiple sizes and refined finishes.",
    desc: "Precision-formed hinges in mild steel, stainless steel and cast iron, covering butt, bearing, flush, parliament, spring and T-hinge patterns. Each hinge is made to tight knuckle and pin tolerances for smooth rotation, accurate door alignment and long service life under repeated cycling.",
    items: [
      item("THMS-101", "Butt Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "75, 100"),
      item("THMS-102", "Bearing Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "75, 100, 102"),
      item("THMS-103", "Loose Pin Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "75, 100"),
      item("THMS-104", "Butt Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "100"),
      item("THMS-105", "Butt Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "25, 40, 50, 75, 100, 125"),
      item("THMS-106", "Bearing Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "75, 100, 102"),
      item("THSS-101", "Butt Hinge", "Stainless Steel (202 grade)", "Satin, Mirror", "75, 100"),
      item("THMS-107", "Half Round Flush Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "75, 100"),
      item("THMS-108", "Half Square Flush Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "65"),
      item("THMS-109", "Flush Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "40, 50"),
      item("THMS-110", "Stormproof Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "63"),
      item("THMS-111", "Double Cranked Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "50"),
      item("THMS-112", "Butt Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "13"),
      item("THMS-113", "Parliament Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "100"),
      item("THMS-114", "Back Flap Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "25, 40, 50, 65"),
      item("THMS-115", "Spring Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "65"),
      item("THMS-116", "Butterfly Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "63"),
      item("THMS-117", "Bolt Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "75, 100, 125"),
      item("THCI-101", "T-Hinge", "Cast Iron", "MB"),
      item("THMS-118", "T-Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, An.BP, Ch.St, Ni.St, MB, CuP"),
      item("THCI-102", "T-Hinge", "Cast Iron", "MB"),
      item("THMS-119", "T-Hinge", "Mild Steel (MS)", "SC, ZP, BP, CP, An.BP, Ch.St, Ni.St, MB, CuP"),
    ],
  },
  {
    slug: "locks",
    num: "02",
    name: "Locks",
    single: "Lock",
    tagline: "Secure locking solutions crafted for reliable everyday protection.",
    desc: "Mortise locks and tubular latches engineered for secure, dependable door operation. Accurately machined cases, robust internal mechanisms and matched strike plates deliver consistent latching and long-term reliability in residential and commercial doors.",
    items: [
      item("TLMS-101", "Mortise Lock", "Mild Steel (MS)", "CP, BP, ZP, Satin", "70"),
      item("TLMS-102", "Mortise Lock", "Mild Steel (MS)", "CP, BP, ZP, Satin", "70"),
      item("TLMS-103", "Mortise Lock", "Mild Steel (MS)", "CP, BP, ZP, Satin", "65"),
      item("TLMS-104", "Tubular Latch", "Mild Steel (MS)", "ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "65, 75"),
      item("TLMS-105", "Bolt Through Tubular Latch", "Mild Steel (MS)", "ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "65, 75"),
      item("TLMS-106", "Tubular Latch", "Mild Steel (MS)", "ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "65, 75"),
      item("TLMS-107", "Tubular Latch", "Mild Steel (MS)", "ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "65, 75"),
    ],
  },
  {
    slug: "door-handles",
    num: "03",
    name: "Door Handles",
    single: "Door Handle",
    tagline: "Elegant door handles designed for comfort, durability and style.",
    desc: "Lever and pull handles in zinc, mild steel, stainless steel, aluminium, brass and cast iron. Each handle is balanced for a comfortable grip and finished to resist wear, ensuring reliable operation under frequent daily use.",
    items: [
      item("TDHZ-101", "Door Handle", "Zinc", "CP, SS", "200"),
      item("TDHZ-102", "Door Handle", "Zinc", "CP, MB, BP", "200"),
      item("TDHMS-103", "Door Handle", "Mild Steel (MS), Aluminium", "CP, NS, Br.Ant", "200"),
      item("TDHSS-104", "Door Handle", "Stainless Steel", "SS, MB", "200"),
      item("TDHSS-105", "Door Handle", "Stainless Steel", "SS, MB", "200"),
      item("TDHMS-106", "Door Handle", "Mild Steel (MS), Aluminium", "CP, NSs, BSs", "150"),
      item("TDHMS-107", "Door Handle", "Mild Steel (MS), Aluminium", "CP, NSs, BSs", "150"),
      item("TDHMS-108", "Door Handle", "Mild Steel (MS), Aluminium", "CP, MB", "150"),
      item("TDHMS-109", "Door Handle", "Mild Steel (MS), Stainless Steel", "Satin, Mirror"),
      item("TDHMS-110", "Door Handle", "Mild Steel (MS), Stainless Steel", "Satin, Mirror"),
      item("TDHSS-111", "Door Handle", "Stainless Steel (202 grade)", "SS, MB"),
      item("TDHSS-112", "Door Handle", "Stainless Steel (202 grade)", "SS, MB"),
      item("TDHSS-113", "Door Handle", "Stainless Steel (202 grade)", "SS, MB"),
      item("TDHAL-114", "Door Handle", "Aluminium", "SS, MB"),
      item("TDHAL-115", "Door Handle", "Aluminium", "SS, MB"),
      item("TDHAL-116", "Door Handle", "Aluminium", "SS, MB"),
      item("TDHZ-117", "Door Handle", "Cast Iron", "MB"),
      item("TDHZ-118", "Door Handle", "Cast Iron", "MB"),
      item("TDHZ-119", "Door Handle", "Cast Iron", "MB"),
      item("TDHZ-120", "Door Handle", "Cast Iron", "MB"),
      item("TDHMS-120", "Door Handle", "Brass, Mild Steel (MS)", "All finishes", "100, 150, 200"),
      item("TDHMS-121", "Door Handle", "Brass, Mild Steel (MS)", "All finishes", "100, 150, 200"),
      item("TDHMS-122", "Door Handle", "Brass, Mild Steel (MS)", "All finishes", "100, 150, 200"),
      item("TDHMS-123", "Door Handle", "Brass, Mild Steel (MS)", "All finishes", "100, 150, 200"),
      item("TDHMS-124", "Door Handle", "Brass, Mild Steel (MS)", "All finishes", "100, 150, 200"),
      item("TDHMS-125", "Door Handle", "Brass, Mild Steel (MS)", "All finishes", "100, 150, 200"),
      item("TDHMS-126", "Door Handle", "Brass, Mild Steel (MS)", "All finishes", "100, 150, 200"),
    ],
  },
  {
    slug: "brackets",
    num: "04",
    name: "Brackets",
    single: "Bracket",
    tagline: "Strong, versatile brackets for shelves, furniture and architectural applications.",
    desc: "Load-bearing brackets in brass and mild steel for shelving, furniture and architectural fixing. Rigid profiles and accurately punched fixing holes provide stable, deflection-resistant support.",
    items: [
      item("TBB-101", "Bracket", "Brass", "SC, ZP, BP, CP, An.BP, Ch.St, Ni.St, MB, CuP"),
      item("TBB-102", "Bracket", "Brass", "SC, ZP, BP, CP, An.BP, Ch.St, Ni.St, MB, CuP"),
      item("TBB-103", "Bracket", "Mild Steel (MS)", "ZP, BP, MB", "25, 50, 75, 100"),
      item("TBB-104", "Bracket", "Brass", "CP, St.Ni, St.Ch, Ant.BP", "16"),
    ],
  },
  {
    slug: "hooks",
    num: "05",
    name: "Hooks",
    single: "Hook",
    tagline: "Functional hooks combining everyday utility with refined design.",
    desc: "Robe, coat and utility hooks in brass, mild steel, cast iron and ceramic. Solid construction and secure screw-fixing points provide dependable load holding in homes, offices and commercial interiors.",
    items: [
      item("THB-101", "Hook", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("THB-102", "Hook", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("THB-103", "Hook", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("THB-104", "Hook", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("THB-105", "Hook", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("THB-106", "Hook", "Mild Steel (MS)", "CP, MB, St.Ni"),
      item("THB-107", "Hook", "Cast Iron", "MB"),
      item("THB-108", "Hook", "Cast Iron", "MB"),
      item("THB-109", "Hook", "Cast Iron", "MB"),
      item("THB-110", "Hook", "Cast Iron", "MB"),
      item("THB-111", "Hook", "Cast Iron", "MB"),
      item("THB-112", "Hook", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("THB-113", "Hook", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("THB-114", "Hook", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("THB-115", "Hook", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("THB-116", "Hook", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("THB-117", "Hook", "Ceramic", ""),
      item("THB-118", "Hook", "Ceramic", ""),
    ],
  },
  {
    slug: "cabinets",
    num: "06",
    name: "Cabinets",
    single: "Cabinet Hardware",
    tagline: "Refined cabinet hardware designed to add function and character.",
    desc: "Cabinet knobs, pulls, flush handles and alphanumerics in brass, cast iron and ceramic. Each piece is precision-cast and finished for a secure fit and a durable, consistent appearance across joinery.",
    items: [
      item("TCB-101", "Cabinet Hardware", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("TCB-102", "Cabinet Hardware", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("TCB-103", "Cabinet Hardware", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("TCB-104", "Cabinet Hardware", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("TCB-105", "Cabinet Hardware", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("TCB-106", "Cabinet Hardware", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("TCB-107", "Cabinet Hardware", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("TCB-108", "Cabinet Hardware", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("TCB-109", "Cabinet Hardware", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("TCB-110", "Cabinet Hardware", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("TCB-111", "Cabinet Hardware", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("TCB-112", "Cabinet Hardware", "Cast Iron", "MB"),
      item("TCB-113", "Cabinet Hardware", "Ceramic", ""),
      item("TCB-114", "Cabinet Hardware", "Ceramic", ""),
      item("TCB-115", "Cabinet Hardware", "Ceramic", ""),
      item("TCB-116", "Cabinet Hardware", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("TCB-117", "Alphanumeric", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("TCB-118", "Alphanumeric", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
      item("TCB-119", "Cabinet Hardware", "Brass", "CP, St.Ni, St.Ch, Ant.BP"),
    ],
  },
  {
    slug: "pad-brenton-bolts",
    num: "07",
    name: "Pad / Brenton Bolts",
    single: "Pad Bolt",
    tagline: "Reliable bolts designed for secure fastening across doors and gates.",
    desc: "Surface-mounted pad and brenton bolts in mild steel for securing doors, gates and windows. A solid shoot running in a rigid guide gives a smooth throw and positive locking, with provision for a padlock.",
    items: [
      item("TBBMS-101", "Pad Bolt", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "200"),
      item("TBBMS-102", "Pad Bolt", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "150"),
      item("TBBMS-103", "Pad Bolt", "Mild Steel (MS)", "SC, ZP, BP, CP, MB, CuP, An.BP, Ch.St, Ni.St", "100"),
      item("TBBMS-104", "Pad Bolt", "Mild Steel (MS)", "ZP, MB", "100, 150, 200, 250"),
    ],
  },
  {
    slug: "tower-bolts",
    num: "08",
    name: "Tower Bolts",
    single: "Tower Bolt",
    tagline: "Sturdy tower bolts for smooth, dependable door and gate fastening.",
    desc: "Tower bolts in mild steel, cast iron and stainless steel, from 75 mm to 300 mm. A round shoot and matched keep provide smooth, positive fastening for doors, gates, windows and furniture.",
    items: [
      item("TTBMS-101", "Tower Bolt", "Mild Steel (MS)", "ZP, MB", "75, 100, 150, 200, 250, 300"),
      item("TTBCI-102", "Tower Bolt", "Cast Iron", "MB", "150, 200, 250"),
      item("TTBMS-103", "Tower Bolt", "Mild Steel (MS)", "ZP, MB", "75, 100, 150, 200, 250, 300"),
      item("TTBMS-104", "Tower Bolt", "Mild Steel (MS)", "ZP, MB", "75, 100, 150, 200, 250, 300"),
      item("TTBSS-105", "Tower Bolt", "Stainless Steel (202 grade)", "Satin, Mirror", "75, 100, 150, 200, 250, 300"),
    ],
  },
  {
    slug: "cabin-hooks",
    num: "09",
    name: "Cabin Hooks",
    single: "Cabin Hook",
    tagline: "Practical cabin hooks for securely holding doors and windows open.",
    desc: "Hook-and-eye cabin hooks in brass and cast iron, from 100 mm to 300 mm. Designed to hold doors, windows and shutters securely in the open position against wind load and accidental closing.",
    items: [
      item("TCHB-101", "Cabin Hook", "Brass", "CP, Satin, St.CP, St.Ni", "100, 150, 200, 250, 300"),
      item("TCHCI-102", "Cabin Hook", "Cast Iron", "MB", "100, 150, 200, 250, 300"),
      item("TCHCI-103", "Cabin Hook", "Cast Iron", "MB", "100, 150, 200, 250, 300"),
    ],
  },
  {
    slug: "gate-latch",
    num: "10",
    name: "Gate Latch",
    single: "Gate Latch",
    tagline: "Durable gate latches designed for secure, effortless everyday use.",
    desc: "Ring and iron gate latches in mild steel and cast iron. A robust latch bar and heavy-duty keep deliver secure, positive latching for garden, yard and industrial gates.",
    items: [
      item("TGLMS-101", "Ring Latch", "Mild Steel (MS)", "ZP, MB"),
      item("TGLCI-102", "Iron Gate Latch", "Cast Iron", "MB"),
      item("TGLMS-103", "Ring Latch", "Mild Steel (MS)", "ZP, MB"),
      item("TGLCI-104", "Iron Gate Latch", "Cast Iron", "MB"),
    ],
  },
];

// Product-level descriptions, keyed by internal catalogue reference
const productDescs: Record<string, string> = {
  "THMS-101": "A classic mild steel butt hinge, shown here in bright chrome and polished brass finishes. Precision-pressed leaves and a tightly fitted pin give a smooth, quiet swing and accurate door alignment, while the plated finish protects against corrosion and daily wear. Available in 75 and 100 mm, it is the everyday choice for interior doors, cupboards and windows in homes, apartments, offices and commercial fit-outs.",
  "THMS-102": "A heavy-duty mild steel bearing hinge with ball-bearing knuckles that carry the door's weight with minimal friction, keeping heavy doors swinging smoothly and silently. Shown in satin and matt black finishes, its reinforced leaves are built for high-traffic use and a long service life. Ideal for main entrance doors, corridor and fire doors in hotels, hospitals, offices and institutional buildings.",
  "THMS-103": "A mild steel loose pin hinge with a removable pin, so doors can be lifted off for installation, painting or maintenance without unscrewing the leaves. Finial-tipped knuckles add a neat decorative touch, and the durable plated finish resists everyday wear. Well suited to residential interiors, offices, hospitality projects, retail fit-outs and service areas.",
  "THMS-104": "A broad, heavy-gauge mild steel butt hinge with eight countersunk fixing holes that spread the load and hold the door firmly in line. Its solid square-edged leaves and smooth-running knuckle are made for heavier doors and frequent use. Recommended for main doors, commercial and office doors, schools, hospitals and public buildings.",
  "THMS-105": "A mild steel butt hinge available in the widest size range, from compact 25 mm up to 125 mm, to suit everything from small cabinet doors to full-size room doors. Accurately formed leaves and a firm pin ensure a stable, smooth action, and a choice of nine finishes, including the antique tone shown, matches any interior. Used across furniture, joinery, residential and commercial projects.",
  "THMS-106": "A mild steel bearing hinge, shown in a rich copper finish, fitted with bearing rings that reduce wear at the knuckle and keep doors moving freely year after year. Heavy leaves and precise machining give excellent load capacity and alignment on heavier doors. Suited to premium residential doors, hotel rooms, offices and hospitality interiors where both performance and appearance matter.",
  "THSS-101": "A premium stainless steel (202 grade) butt hinge that combines strength with excellent resistance to rust, moisture and cleaning chemicals. Satin and mirror finishes give a clean, contemporary look that stays bright with minimal maintenance. The right choice for kitchens, bathrooms, coastal homes, hospitals, laboratories and hotels.",
  "THMS-107": "A mild steel half-round flush hinge whose shaped leaves fold into one another, so it fits without cutting a mortise in the door or frame. The decorative rounded leaf gives a neat, finished look while saving installation time. Ideal for wardrobes, kitchen cabinets, lightweight interior doors and modular furniture.",
  "THMS-108": "A compact 65 mm mild steel half-square flush hinge with straight-edged, interlocking leaves that sit flat when closed and need no mortising. Quick to fit and reliable in daily use, it gives furniture and cabinet doors a clean, tidy appearance. Widely used in modular kitchens, wardrobes, office furniture and joinery workshops.",
  "THMS-109": "A small 40\u201350 mm mild steel flush hinge for light doors and panels, fitted directly to the surface without a recess. Its slim, low-profile leaves close neatly, and the durable plating keeps it looking good over time. Perfect for cabinets, cupboards, boxes, display units and furniture.",
  "THMS-110": "A 63 mm mild steel stormproof hinge made for casement windows where the sash closes over the frame, giving a secure, weather-tight hang. Strong, cranked leaves and protective finishes cope well with outdoor exposure and constant opening. Commonly used on timber windows in homes, cottages, schools and heritage restorations.",
  "THMS-111": "A 50 mm mild steel double cranked hinge whose offset leaves let a door or sash swing clear of its frame, making it ideal for rebated and flush-fitting joinery. Solid construction and hard-wearing finishes ensure dependable movement for years. Frequently specified for casement windows, cupboard doors and bespoke furniture.",
  "THMS-112": "A miniature 13 mm mild steel butt hinge made for small boxes, cases and fine joinery where a discreet pivot is needed. Despite its size, it is precisely formed for a smooth, stable action, with a bright plated finish. Popular with furniture makers and for jewellery boxes, gift packaging, display cases and craft work.",
  "THMS-113": "A 100 mm mild steel parliament hinge with extended, projecting knuckles that let the door open a full 180\u00b0 and clear architraves, deep reveals and mouldings. Strong leaves and a well-fitted pin keep heavy doors securely aligned. Ideal for French doors, patio doors, shutters and traditional or institutional buildings.",
  "THMS-114": "A mild steel back flap hinge with wide, square leaves that spread the load over a large fixing area, giving flaps and fold-down panels a strong, stable pivot. Available from 25 to 65 mm with durable plated finishes. Used on table leaves, drop-down counters, shutters, chests, trap doors and furniture.",
  "THMS-115": "A 65 mm self-closing mild steel spring hinge that brings the door gently back to the closed position after every use. Its internal spring is built for long, repeated cycling, helping maintain privacy, hygiene and temperature control. Widely used in kitchens, restaurants, hospitals, offices, public washrooms and commercial premises.",
  "THMS-116": "A 63 mm mild steel butterfly hinge that pairs a decorative, winged profile with dependable strength. Precisely formed leaves and a firm pin give smooth movement, while quality finishes add a refined touch. Perfect for cabinets, jewellery and gift boxes, cupboards and antique-style furniture.",
  "THMS-117": "A mild steel bolt hinge with a sturdy integrated pin that provides a strong, secure pivot for heavier doors and gates. Available in 75, 100 and 125 mm, its robust construction and hard-wearing finishes handle frequent use in demanding conditions. Suitable for utility doors, gates, sheds, warehouses and industrial units.",
  "THCI-101": "A cast iron T-hinge with a decorative spear-point strap and a matt black finish, combining traditional styling with heavy-duty strength. The long strap spreads the load across the door, keeping ledged and boarded doors from sagging. Ideal for gates, barn and stable doors, garden structures and heritage properties.",
  "THMS-118": "A plain mild steel T-hinge with a long tapered strap that spreads door weight evenly and prevents sagging on wide or heavy doors. Offered in a broad range of protective finishes, it performs reliably indoors and outdoors. Commonly used on gates, garden and utility doors, sheds, garages and farm buildings.",
  "THCI-102": "An ornamental cast iron T-hinge with a hand-forged look, a textured strap and a durable matt black finish. Strong and long-lasting outdoors, it gives doors and gates an authentic period character. Suited to cottages, heritage buildings, resorts, garden gates and rustic interiors.",
  "THMS-119": "A mild steel T-hinge, shown in a bright brass-plated finish, that pairs a long load-spreading strap with a compact leaf for the frame. It gives lighter doors and lids a strong, neat hinge with a decorative finish. Ideal for cabinets, chests, garden furniture, sheds and utility doors.",
  "TLMS-101": "A 70 mm mild steel mortise sashlock with a black body and a cylinder operation, fitted inside the door for a clean, secure installation. Its precisely engineered latch and deadbolt work smoothly day after day, supported by a matched strike plate and keys. Used on main and internal doors in homes, apartments, offices and hotels.",
  "TLMS-102": "A 70 mm mild steel lever mortise lock with a zinc-plated case, brass-finished bolts and lever keys, offering proven, dependable security. Its robust internal mechanism is built for years of reliable locking. Suited to residential doors, offices, schools, hospitals and institutional buildings.",
  "TLMS-103": "A compact 65 mm mild steel mortise lock with a black case, brass-finished latch and deadbolt, and key operation. It fits neatly into standard doors and gives smooth, secure locking with a long service life. Ideal for bedrooms, offices, store rooms and commercial interiors.",
  "TLMS-104": "A mild steel tubular latch with a brass-finished latch bolt and a matching strike, giving smooth, positive latching with a quiet action. Compact and easy to fit in 65 or 75 mm backsets, it is built from durable, plated components. Suited to internal doors in homes, offices, hotels and schools, paired with lever or knob handles.",
  "TLMS-105": "A heavy-duty bolt-through tubular latch that fixes through the door with bolts for extra strength and stability under constant use. Its precision latch mechanism closes smoothly and positively every time. Ideal for high-traffic doors in commercial offices, hotels, hospitals, schools and public buildings.",
  "TLMS-106": "A mild steel tubular latch with a contrasting black forend and strike plate, designed to match dark and matt black door hardware. It gives smooth, reliable latching in 65 or 75 mm backsets and a long, trouble-free life. Popular for modern homes, offices, boutique hotels and contemporary interiors.",
  "TLMS-107": "A mild steel tubular latch with a brass-finished forend and strike, made to complement brass and gold-tone handles. Quiet, smooth and easy to install, it provides dependable everyday latching. Suited to residential interiors, hospitality projects and premium office fit-outs.",
  "TDHZ-101": "A slim zinc alloy lever handle on a narrow plate with a keyhole, shown in bright chrome. Precision die-cast for a solid, balanced feel, it suits narrow door stiles and fits standard mortise locks. Ideal for apartments, bedrooms, offices and hotel rooms.",
  "TDHZ-102": "A zinc alloy lever handle with a satin lever set against a bold black plate for a striking contemporary look. The ergonomic lever gives a comfortable grip, and the durable finish resists wear and tarnish. Popular in modern homes, offices, showrooms and hospitality interiors.",
  "TDHMS-103": "A 200 mm lever handle on plate, made from mild steel and aluminium, with a decorative sculpted plate in an antique brass finish. It combines strength with a classic, elegant look that adds character to any door. Suited to traditional homes, heritage properties, hotels and premium residential projects.",
  "TDHSS-104": "A 200 mm stainless steel lever handle on plate with a tubular lever and ribbed detailing. Strong, hygienic and resistant to rust and moisture, it keeps its finish in busy environments with minimal maintenance. Ideal for offices, hospitals, laboratories, hotels and modern homes.",
  "TDHSS-105": "A 200 mm stainless steel lever handle on a rounded plate with a straight, minimalist lever. It offers excellent corrosion resistance and a clean, modern appearance that suits any setting. Widely used in commercial offices, clinics, schools and contemporary residences.",
  "TDHMS-106": "A 150 mm lever handle on plate in mild steel and aluminium, with a gracefully curved lever for a comfortable, natural grip. The durable plated finish keeps it looking sharp through years of use. Suited to bedrooms, living areas, offices and hospitality interiors.",
  "TDHMS-107": "A 150 mm lever handle on a squared plate with a flowing scroll lever, made from mild steel and aluminium. It combines a classic profile with a sturdy build for everyday reliability. Ideal for homes, apartments, hotels and traditional-style interiors.",
  "TDHMS-108": "A 150 mm lever handle on plate, in mild steel and aluminium, with a swept, sculpted lever and a keyhole for mortise locks. Balanced for smooth operation and finished in chrome or matt black, it is built to last. Used on residential, office and commercial doors.",
  "TDHMS-109": "A round escutcheon with a profile-cylinder cut-out, made from mild steel and stainless steel to finish and protect the lock cylinder on the door face. Satin and mirror finishes match our lever handles for a co-ordinated look. Used across homes, offices, hotels and commercial doors.",
  "TDHMS-110": "A round rose with a thumb-turn, made from mild steel and stainless steel, for simple privacy locking on bathroom and bedroom doors. It turns smoothly and positively, and its satin or mirror finish resists everyday wear. Ideal for homes, hotels, hospitals and office washrooms.",
  "TDHSS-111": "A stainless steel (202 grade) lever handle on round rose with a smooth, rounded return lever that is comfortable to use and safe on clothing. Strong, corrosion-resistant and easy to clean, it suits busy environments. Ideal for hospitals, schools, offices and public buildings.",
  "TDHSS-112": "A stainless steel (202 grade) straight lever handle on round rose with a sleek, minimalist profile. Its solid construction and corrosion-resistant finish keep it reliable and attractive with minimal upkeep. Popular in modern homes, offices, hotels and retail spaces.",
  "TDHSS-113": "A stainless steel (202 grade) lever handle on round rose with a mitred, angled lever for a sharp architectural look. Built for strength and easy cleaning, it performs well in high-use settings. Suited to contemporary offices, hotels, showrooms and premium residences.",
  "TDHAL-114": "A black aluminium window handle with a slim lever on a compact base, designed for smooth locking of aluminium and uPVC windows. Lightweight yet strong, it resists corrosion and is easy to maintain. Widely used in residential projects, apartments, offices and commercial buildings.",
  "TDHAL-115": "A black aluminium handle with a curved lever and a low-profile base, giving a firm, comfortable grip on windows and sliding doors. The corrosion-resistant finish keeps it looking clean in all conditions. Ideal for uPVC and aluminium systems in homes, offices and high-rise developments.",
  "TDHAL-116": "A black aluminium handle with a broad, sculpted lever that gives a secure, comfortable grip and easy operation. Durable, lightweight and corrosion-resistant, it suits both doors and windows. Used in aluminium and uPVC fenestration for residential and commercial projects.",
  "TDHZ-117": "An ornate cast iron lever handle on a long, decorative backplate with a keyhole, in a durable matt black finish. Solid and weighty, it brings authentic period character along with exceptional strength. Perfect for heritage homes, cottages, farmhouses, resorts and rustic interiors.",
  "TDHZ-118": "A cast iron D pull handle mounted on round roses, with a hand-forged look and a matt black finish. Its sturdy build provides a firm grip and lasting durability, indoors and outdoors. Ideal for gates, barn and stable doors, sheds, cabinets and rustic furniture.",
  "TDHZ-119": "A cast iron bar pull handle with pointed finials and an elongated backplate, finished in matt black. Strong and long-lasting, it adds a traditional, forged look to doors and gates. Suited to heritage properties, farmhouses, restaurants, resorts and garden gates.",
  "TDHZ-120": "A cast iron pull handle with decorative fleur-de-lis ends in a durable matt black finish. It combines ornamental styling with a solid, secure grip. Perfect for period doors, cupboards, garden gates, caf\u00e9s and heritage-style interiors.",
  "TDHMS-120": "A classic D-shaped pull handle in brass and mild steel, available in 100, 150 and 200 mm and in all finishes. Its rounded grip is comfortable to use, and the solid build and secure fixings stand up to frequent daily use. Used on doors, cabinets, wardrobes, drawers and shop fittings.",
  "TDHMS-121": "An angled bow pull handle in brass and mild steel with a modern, faceted profile. Offered in 100, 150 and 200 mm and all finishes, it provides a strong, comfortable grip. Ideal for kitchen cabinets, wardrobes, office furniture and contemporary joinery.",
  "TDHMS-122": "A cranked pull handle in brass and mild steel with stepped, offset ends that give extra finger clearance. Available in 100, 150 and 200 mm in all finishes, it combines strength with a distinctive look. Suited to doors, cabinets, drawers and retail fit-outs.",
  "TDHMS-123": "A square-profile bar pull handle in brass and mild steel with clean, straight lines. Offered in 100, 150 and 200 mm and all finishes, it is built for reliable everyday use. Popular for modular kitchens, wardrobes, office furniture and modern interiors.",
  "TDHMS-124": "A tubular pull handle in brass and mild steel with rounded standoffs for a secure, comfortable grip. Available in 100, 150 and 200 mm and all finishes, it suits both doors and furniture. Widely used on entrance doors, cabinets, shop fronts and commercial joinery.",
  "TDHMS-125": "A gently curved bow pull handle in brass and mild steel with a slim, elegant profile. Offered in 100, 150 and 200 mm and all finishes, it adds a refined touch while giving a firm grip. Ideal for wardrobes, drawers, cabinets and premium furniture.",
  "TDHMS-126": "A raised, cranked pull handle in brass and mild steel with sloping legs for a bold, contemporary silhouette. Available in 100, 150 and 200 mm in all finishes, it is strong and comfortable in daily use. Suited to doors, cabinets, kitchens and office furniture.",
  "TBB-101": "A solid brass L-shaped shelf bracket with a curved support arm, shown in polished brass and chrome. It holds shelves firmly with secure fixing points, and resists corrosion in a wide range of finishes. Ideal for kitchens, living rooms, libraries, caf\u00e9s and retail displays.",
  "TBB-102": "A solid brass shelf bracket with a decorative curved brace, combining classic styling with dependable load-bearing strength. Precision-made with secure fixings and available in many finishes. Perfect for homes, hotels, boutique shops, restaurants and period interiors.",
  "TBB-103": "A zinc-plated mild steel angle bracket for strong, rigid corner joints in timber and board construction. Available in 25, 50, 75 and 100 mm, with accurately punched holes for quick fixing and long-lasting support. Widely used in furniture assembly, shelving, joinery, construction and industrial fit-outs.",
  "TBB-104": "A decorative 16 mm solid brass bracket with an ornamental rose, designed to support curtain rods securely and elegantly. Its solid construction and premium finishes resist tarnishing and daily use. Ideal for homes, hotels, offices, banquet halls and premium interiors.",
  "THB-101": "A solid brass three-arm hat and coat hook with a tall upper arm and two curved side hooks, finished in polished brass. It holds coats, hats and bags securely and resists tarnishing over time. Ideal for entrance halls, hotel rooms, offices, cloakrooms and hospitality interiors.",
  "THB-102": "A solid brass double robe hook with rounded arms and a looped top, offering generous hanging space in a compact footprint. Strong, corrosion-resistant and elegantly finished for daily use. Suited to bathrooms, bedrooms, changing rooms and hotel suites.",
  "THB-103": "A solid brass swivel hook with three folding arms that swing out when needed and fold flat against the wall when not in use. Space-saving and strong, it is ideal for towels, garments and accessories. Perfect for bathrooms, wardrobes, hotel rooms and compact spaces.",
  "THB-104": "A solid brass hat and coat hook in a satin nickel finish, with a sweeping upper arm and a smaller lower hook. Sturdy and corrosion-resistant, it holds coats and bags securely day after day. Ideal for homes, offices, schools, hospitals and cloakrooms.",
  "THB-105": "A solid brass double coat hook with a gracefully curved profile in satin nickel. Its strong construction and durable finish make it a reliable choice for heavy coats and bags. Suited to hallways, offices, hotels, restaurants and changing rooms.",
  "THB-106": "A heavy-duty mild steel wall hook with a round wall plate and a strong curved arm, finished in matt black, chrome or nickel. Built for secure holding of heavier loads, it also works as a handrail or support bracket. Suited to utility rooms, workshops, stores, stairways and commercial facilities.",
  "THB-107": "A cast iron multi-hook rail with three hooks on a single backplate, in a durable matt black finish. It gives plenty of hanging space for coats, bags, keys or tools in one strong fitting. Ideal for entrances, mudrooms, farmhouses, caf\u00e9s and rustic interiors.",
  "THB-108": "A cast iron double robe hook with twin curled arms and a matt black finish. Solid and long-lasting, it holds towels, robes and garments securely. Perfect for bathrooms, bedrooms, cottages and heritage-style interiors.",
  "THB-109": "A cast iron hat and coat hook with a tall bulb-tipped upper arm and a curved lower hook, finished in matt black. Exceptionally strong, it is made for heavy coats and everyday use. Ideal for hallways, farmhouses, restaurants, resorts and workshops.",
  "THB-110": "A compact cast iron single robe hook with a teardrop backplate and a matt black finish. Small but sturdy, it is perfect for towels, keys, bags and light garments. Suited to bathrooms, kitchens, caf\u00e9s and rustic interiors.",
  "THB-111": "A cast iron single hook with a long, tapered arm and bulb end, in a durable matt black finish. Its extended reach and solid construction make it ideal for heavier items. Used in cloakrooms, stables, workshops, garden sheds and heritage properties.",
  "THB-112": "A solid brass single robe hook with a double-curved arm and a compact base, finished in polished brass. Strong, tarnish-resistant and neat in appearance for everyday use. Ideal for bathrooms, bedrooms, wardrobes and hotel rooms.",
  "THB-113": "A solid brass cleat hook with two opposing horns, designed for securing ropes, cords and blind cords neatly. Strong and corrosion-resistant, it performs reliably in both home and marine settings. Suited to window blinds, flagpoles, boats, awnings and utility areas.",
  "THB-114": "A solid brass horizontal cleat with ball ends, used to tie off and secure cords, ropes and chains. Its sturdy build and corrosion-resistant finish make it suitable indoors and outdoors. Ideal for blinds, curtains, marine fittings and display installations.",
  "THB-115": "A solid brass screw-in hook with a decorative ball tip and a threaded shank that fixes directly into wood without a backplate. Quick to install and strong in use, it is ideal for hanging pictures, cups, plants and light fittings. Popular in homes, caf\u00e9s, retail displays and workshops.",
  "THB-116": "A solid brass screw-in cup hook with a round collar and a curved open hook for fast hanging and removal. Simple to fit, strong and resistant to tarnishing. Ideal for kitchen cabinets, mug racks, pantries, displays and craft work.",
  "THB-117": "A decorative wall hook topped with a hand-painted ceramic knob in a cream and gold pattern, on a sturdy metal stem. It adds a charming artisan touch while holding clothes, bags and towels securely. Popular in homes, boutiques, caf\u00e9s and hospitality interiors.",
  "THB-118": "A decorative wall hook with a white ceramic knob featuring a striped pattern, on a strong metal stem. Easy to fit and built for everyday use, it brings character to walls and doors. Ideal for bedrooms, children's rooms, boutiques and hotel rooms.",
  "TCB-101": "An ornate solid brass bail pull with a richly detailed Victorian-style backplate and keyhole. Finished to a high standard, it gives drawers and cabinets a classic, luxurious look while providing a firm, comfortable grip. Ideal for antique restoration, period furniture, dressers and hospitality interiors.",
  "TCB-102": "A solid brass drop pull with a rounded bail on a compact rectangular mount. Its solid build and smooth action make it ideal for everyday use on drawers and chests. Suited to campaign-style furniture, cabinets, wardrobes and bespoke joinery.",
  "TCB-103": "A solid brass bail pull with an intricate filigree backplate, combining decorative craftsmanship with reliable strength. Its premium finish resists tarnishing and daily handling. Perfect for traditional dressers, sideboards, cabinets and antique reproductions.",
  "TCB-104": "A solid brass ring pull hanging from a stepped, concentric rose, giving a classic and elegant look. The ring provides a comfortable grip and the solid construction ensures long life. Ideal for drawers, cupboards, chests and period furniture.",
  "TCB-105": "A solid brass ring pull on a beaded, domed rose, crafted for a refined, traditional appearance. Strong and tarnish-resistant, it is made for frequent use. Suited to cabinets, drawers, dressers and hospitality furniture.",
  "TCB-106": "A solid brass bail pull with a decorative Chippendale-style backplate. Its bold, shaped plate protects the furniture surface while the bail gives a firm grip. Perfect for traditional chests of drawers, bureaus, sideboards and antique restoration.",
  "TCB-107": "A solid brass recessed ring pull that sits flush with the surface when not in use, ideal where projecting handles would get in the way. Strong and corrosion-resistant, it suits both furniture and marine joinery. Used on sliding doors, trunks, boats, cabinets and built-in furniture.",
  "TCB-108": "A solid brass bail pull with an ornate oval pierced backplate for a delicate, decorative finish. Crafted for durability and a comfortable grip. Ideal for dressers, jewellery cabinets, vanity units and period-style furniture.",
  "TCB-109": "A solid brass teardrop drop pull hanging from an ornamental floral rose. Its elegant profile adds a touch of luxury to small drawers and doors. Perfect for dressing tables, bedside cabinets, jewellery boxes and hospitality furniture.",
  "TCB-110": "A solid brass decorative drop pull with a looped, ornate handle on a round rose. Precision-cast and finished to resist tarnishing, it combines strength with a distinctive look. Suited to cabinets, drawers, wardrobes and boutique interiors.",
  "TCB-111": "A solid brass drop handle with a bold looped grip on a round rose, sturdy enough for larger drawers and doors. Its premium finish and solid construction ensure long-lasting performance. Ideal for chests, wardrobes, sideboards and heritage furniture.",
  "TCB-112": "A cast iron ring pull with a textured rose and a durable matt black finish. Strong and long-lasting, it provides a secure grip on cabinets, drawers and doors. Ideal for rustic and heritage furniture, farmhouses, resorts and period interiors.",
  "TCB-113": "A set of hand-painted ceramic cabinet knobs in rich blue, red and green floral designs, each fixed with a sturdy metal bolt. They bring vibrant, artisan colour to furniture and are built for daily use. Popular for kitchens, dressers, children's rooms and boutique interiors.",
  "TCB-114": "A set of ceramic cabinet knobs in cream, red and blue hand-painted floral patterns, with durable metal fixings. Each knob adds character while providing a comfortable, secure grip. Ideal for wardrobes, drawers, kitchen cabinets and hospitality furniture.",
  "TCB-115": "A set of ceramic cabinet knobs in soft yellow, green and blue hand-painted designs on strong metal bolts. They combine craftsmanship with reliable everyday use. Perfect for cottage kitchens, bedrooms, nurseries, caf\u00e9s and boutiques.",
  "TCB-116": "A rectangular solid brass flush pull with a recessed grip that sits level with the surface, ideal where projecting handles are not wanted. Precision-made and corrosion-resistant for long life. Used on sliding doors, wardrobes, cabinets and built-in furniture in homes, offices and hotels.",
  "TCB-117": "Solid brass letters in a classic serif style for clear, durable identification of homes, doors and premises. Precision-cut and finished to resist tarnishing, they stay legible and attractive for years. Used for house names, apartment blocks, offices and hotel signage.",
  "TCB-118": "Solid brass numerals from 0 to 9 in an elegant serif style for door, house and room numbering. Durable, tarnish-resistant and easy to fix, they remain clearly readable over time. Ideal for homes, apartments, hotel rooms, offices and commercial premises.",
  "TCB-119": "A solid brass door stop with a rubber-tipped buffer that protects walls, doors and furniture from impact damage. Its robust construction withstands daily use, and the premium finish resists tarnishing. Ideal for homes, hotels, offices, hospitals and commercial buildings.",
  "TBBMS-101": "A 200 mm heavy-duty mild steel pad bolt with a solid sliding shoot and a padlock staple, for secure locking of doors and gates. Its zinc-plated finish resists rust and weather. Widely used on gates, sheds, garages, stores and warehouses.",
  "TBBMS-102": "A 150 mm mild steel pad bolt with a robust guide, sliding shoot and padlock provision, built to resist tampering and daily wear. Available in a wide range of finishes for indoor and outdoor use. Suited to utility doors, garden gates, store rooms and farm buildings.",
  "TBBMS-103": "A compact 100 mm mild steel pad bolt with padlock staple, ideal for lighter doors, cabinets and hatches that still need secure locking. Strong, corrosion-resistant and easy to fit. Used on cupboards, sheds, service hatches and utility areas.",
  "TBBMS-104": "A heavy-duty mild steel pad bolt in matt black or zinc finish, available from 100 to 250 mm, with a strong shoot and padlock staple. Built for maximum security and durability on outdoor doors and gates. Ideal for warehouses, factories, farms, garages and industrial premises.",
  "TTBMS-101": "A mild steel tower bolt with a round shoot and padlock provision, finished in matt black or zinc. Available from 75 to 300 mm, it gives simple, secure fastening that resists weather and wear. Used on doors, gates, windows and shutters in homes, offices and warehouses.",
  "TTBCI-102": "A cast iron tower bolt with an ornamental body and a durable matt black finish, available in 150, 200 and 250 mm. Strong and long-lasting, it provides secure fastening for heavier doors and gates. Ideal for heritage homes, stable and barn doors, farmhouses and garden gates.",
  "TTBMS-103": "A mild steel tower bolt with a straight round shoot running in a solid guide and a matched keep, finished in matt black or zinc. Available from 75 to 300 mm, it gives smooth, positive fastening. Commonly used on doors, windows, cupboards and shutters.",
  "TTBMS-104": "A slim, extended mild steel tower bolt for tall doors and double doors where a longer throw is needed. Available up to 300 mm in matt black or zinc, it delivers reliable, rigid fastening. Suited to French doors, garage doors, warehouses and industrial units.",
  "TTBSS-105": "A stainless steel (202 grade) tower bolt offering strong, rust-resistant fastening with a smooth sliding action. Satin and mirror finishes keep it clean and attractive, even in humid conditions. Ideal for bathrooms, kitchens, hospitals, hotels and coastal properties.",
  "TCHB-101": "A solid brass cabin hook and eye that holds doors, windows and shutters securely open and stops them slamming in the wind. Precision-made and corrosion-resistant, it is available from 100 to 300 mm in premium finishes. Used in homes, hotels, marine interiors, heritage properties and offices.",
  "TCHCI-102": "An ornamental cast iron cabin hook with decorative mounting plates and a matt black finish, built to hold doors, gates and shutters firmly open. Strong and weather-resistant, it is available from 100 to 300 mm. Ideal for farmhouses, stables, gardens and heritage buildings.",
  "TCHCI-103": "A cast iron cabin hook with a twisted hook arm and ornate backplates, in a durable matt black finish. It provides a secure hold in all conditions and brings traditional charm to any door. Suited to cottages, barns, resorts and rustic interiors, from 100 to 300 mm.",
  "TGLMS-101": "A mild steel ring latch set with a ring handle, latch bar and keep, offering smooth, secure operation from either side of the door or gate. Robust construction and a zinc or matt black finish resist weather and heavy use. Widely used on garden gates, sheds, yards and utility doors.",
  "TGLCI-102": "A traditional cast iron gate latch with a ring handle and ornamental backplates, finished in matt black. Built for strength and long life outdoors, it provides secure, positive latching every time. Ideal for garden and estate gates, farmhouses, heritage properties and resorts.",
  "TGLMS-103": "A mild steel ring latch with a large ring handle and a long latch bar that engages a sturdy keep. Easy to operate and built to withstand frequent use and weather. Suited to farm gates, garden gates, schools and commercial premises.",
  "TGLCI-104": "A cast iron ring gate latch with decorative spear-point plates and a matt black finish, combining ornamental style with heavy-duty strength. It provides reliable, secure latching on wooden gates and doors. Perfect for heritage entrances, garden gates, farmhouses and rustic properties.",
};

// Number items within each category (01, 02, …) and build their URL slugs, e.g. /products/hinges-02
export const categories: CatalogCategory[] = rawCategories.map((c) => ({
  ...c,
  items: c.items.map((i, n) => {
    const num = String(n + 1).padStart(2, "0");
    return { ...i, num, slug: `${c.slug}-${num}`, desc: productDescs[i.code] ?? c.desc };
  }),
}));

export const allItems = categories.flatMap((c) => c.items.map((i) => ({ ...i, category: c })));

export function findItem(slug: string) {
  return allItems.find((i) => i.slug === slug);
}
